seed: 0
epsilon: 0.0
heuristic_type: Normal

terrain: null
spawn_mode: uniform_hideout_dist
min_distance_from_hideout_to_start: 1000
random_cameras: False
camera_file_path: simulator/camera_locations/original_no_camera_net.txt
mountain_locations:
  - 400, 300
  - 1600, 1800
camera_range_factor: 1.0
observation_terrain_feature: False
random_hideout_locations: False
spawn_range: 350
helicopter_battery_life: 200
helicopter_recharge_time: 40
num_search_parties: 5
terrain_map: simulator/forest_coverage/map_set/0.npy
step_reset: True
camera_net_bool: True
include_camera_at_start: False
include_start_location_blue_obs: True
store_last_k_fugitive_detections: True
num_random_known_cameras: 25
num_random_unknown_cameras: 25
known_hideout_locations: 
  - 2077, 2151
  - 2170, 603
  - 37, 1293
  - 1890, 30
  - 1151, 2369 
  - 356, 78 
  - 1751, 1433 
  - 1638, 1028 
  - 1482, 387 
  - 457, 1221
unknown_hideout_locations: 
  - 234, 2082 
  - 1191, 950 
  - 563, 750 
  - 2314, 86 
  - 1119, 1623 
  - 1636, 2136 
  - 602, 1781 
  - 2276, 1007 
  - 980, 118 
  - 2258, 1598
